FROM node:16-alpine

ARG DATABASE_URL

RUN npm i -g pnpm

RUN mkdir /app
WORKDIR /app

RUN apk add --no-cache --upgrade bash
COPY package.json pnpm-lock.yaml ./

RUN pnpm install

COPY . .

RUN pnpm exec prisma generate

EXPOSE 3000

RUN pnpm build

CMD pnpm exec prisma db push && pnpm start 

