import "./globals.css";
import Header from "./components/header";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <Header></Header>

                {children}
            </body>
        </html>
    );
}
