import "./globals.css";
import Header from "./components/header";
import { auth } from "../lib/lucia";
import { AuthRequest } from "@lucia-auth/nextjs";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children, user }) {
    console.log(user);
    return (
        <html lang="en">
            <body>
                <Header></Header>

                {children}
            </body>
        </html>
    );
}

export const getServerSideProps = async (context) => {
    const authRequest = new AuthRequest(auth, context.req, context.res);
    const user = await authRequest.validateUser();
    console.log(user);
    return {
        props: { user },
    };
};
